using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace carvao_app.Models.Modelos
{
    public static class ModeloEmail
    {
        public const string EsqueciSenha = "<!DOCTYPE html>\r\n<html lang=\"pt-BR\">\r\n\r\n<head>\r\n    <meta charset=\"UTF-8\">\r\n    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n    <title>Recuperação de Senha</title>\r\n    <style>\r\n        body {\r\n            font-family: Arial, sans-serif;\r\n            background-color: #f5f5f5;\r\n            margin: 0;\r\n            padding: 0;\r\n            color: #333;\r\n        }\r\n\r\n        .email-container {\r\n            background-color: #fff;\r\n            max-width: 600px;\r\n            margin: 20px auto;\r\n            padding: 20px;\r\n            border-radius: 8px;\r\n            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);\r\n            position: relative;\r\n        }\r\n\r\n        .email-container img {\r\n            position: absolute;\r\n            top: 0;\r\n            right: 0;\r\n        }\r\n\r\n        h1 {\r\n            color: #007bff;\r\n            font-size: 24px;\r\n        }\r\n\r\n        p {\r\n            line-height: 1.6;\r\n        }\r\n\r\n        .btn {\r\n            display: inline-block;\r\n            padding: 10px 20px;\r\n            margin: 20px 0;\r\n            background-color: #007bff;\r\n            color: white;\r\n            text-decoration: none;\r\n            border-radius: 4px;\r\n            font-size: 16px;\r\n        }\r\n\r\n        .btn:hover {\r\n            background-color: #0056b3;\r\n        }\r\n\r\n        .footer {\r\n            font-size: 12px;\r\n            color: #888;\r\n            margin-top: 20px;\r\n            text-align: center;\r\n        }\r\n    </style>\r\n</head>\r\n\r\n<body>\r\n    <div class=\"email-container\">\r\n        <h1>Recuperação de Senha</h1>\r\n        <img src=\"URL_IMAGEM/imagens/logo.png\" width=\"250\" alt=\"\">\r\n        <p>Olá,<NOME></p>\r\n        <p>Recebemos uma solicitação para redefinir a senha da sua conta. Se você não fez essa solicitação, por favor,\r\n            ignore este e-mail.</p>\r\n        <p>Para redefinir sua senha, clique no botão abaixo:</p>\r\n        <a href=\"URL_DE_REDEFINICAO\" class=\"btn\">Redefinir Senha</a>\r\n        <p>Se o botão acima não funcionar, copie e cole o link a seguir no seu navegador:</p>\r\n        <p><a href=\"URL_DE_REDEFINICAO\">URL_DE_REDEFINICAO</a></p>\r\n        <p>Obrigado, <br> Equipe de Suporte</p>\r\n        <div class=\"footer\">\r\n            <p>Se você não solicitou a redefinição de senha, nenhuma ação é necessária. Sua senha permanecerá a mesma.\r\n            </p>\r\n            <p>Este é um e-mail automático, por favor, não responda.</p>\r\n        </div>\r\n    </div>\r\n</body>\r\n\r\n</html>";
    }
}
